myapp:
  properties:
   var: A
spring:
  data:
    mongodb:
     host: 127.0.0.1
     port: 27017
     database: db_encuestas
  jackson:
    serialization:
      indent-output: true
  thymeleaf:
    servlet:
      content-type: application/json; charset=utf-8
  application:
    name: api-process-request
  jmx:
    default-domain: jmx-process-request
server:
  port: 8171
info:
  version: "v1"

